on:
  push:
    branches:
      - master

name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build only
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true

      - name: Minify
        run: |
          sudo apt-get install minify -y

          sudo chmod -R 777 public
          cd public
          minify -r -o . .
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
