on:
  push:
    branches:
      - main

name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build only
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true

      - name: Minify
        run: |
          sudo apt-get update
          sudo apt-get install minify -y

          sudo chmod -R 777 public

          minify -r -o minified public
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: minified
